### ISSUE TITLE
Dependence Version

### ISSUE THREAD

**Issue by Oasis-Guo** [eleurent/social-attention#1]
Hi, I am trying to do the experiment. But I got the below error. I think this is because of the verson of pytorch. I am using pytorch 1.3.1. Is it right? Could U list a dependence with its version, so that we can setup the environment.

`  File "/Users/Oasis/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 607, in graph_diagnostic_info
    mod_tensor_val = n_mod.t('value')
RuntimeError: required keyword attribute 'value' has the wrong type
INFO: Finished writing results. You can upload them to the scoreboard via gym.upload('/Users/Oasis/work_space/RL/rl-agents/scripts/out/IntersectionEnv/DQNAgent/ego_attention_2h_20200104-112302_46007')`

**Comment by eleurent** [comment]
Hi,
I am still using pytorch 1.0.1, and did not run into this issue.
You're right, I should update the dependencies of `rl-agents`.
I'll have to investigate this error with pytorch 1.3.1, though...
Thanks for the feedback!

**Comment by Huhu-ooo** [comment]
Hi, I’m using pytorch 1.4.1 and ran into this error, could you tell me how to fix it? Thanks.

**Comment by Huhu-ooo** [comment]
> Hi, I’m using pytorch 1.4.1 and ran into this error, could you tell me how to fix it? Thanks.

sorry……it is pytorch 1.4.0..

**Comment by eleurent** [comment]
Since the creation of this issue, I have bumped up the pytorch dependency and am now using the 1.4.0 version as well. I did not run into this issue. 
Can I ask what command you are using, and post here the complete stack trace?
You may want to uninstall and reinstall `rl-agents` to ensure you have the latest version.

**Comment by Huhu-ooo** [comment]
runfile('/Users/mandevay/logkeyModel_train.py', wdir='/Users/mandevay')
Number of sessions(hdfs_train): 4856
Number of seqs(hdfs_train): 46573
Traceback (most recent call last):

  File "/Users/mandevay/logkeyModel_train.py", line 98, in <module>
    writer.add_graph(model, seq)

  File "/anaconda2/envs/py36/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 707, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose))

  File "/anaconda2/envs/py36/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 295, in graph
    list_of_nodes = parse(graph, trace, args)

  File "/anaconda2/envs/py36/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 219, in parse
    attr_name = node.s('name')

RuntimeError: required keyword attribute 'name' has the wrong type


That is my complete traceback.
And the latest tensorboard in my anaconda is 2.0.0, but the blogger who created this code used the version2.0.2. 
I cannot make sure if it is the key but I cannot update it to 2.0.2...

**Comment by eleurent** [comment]
I just tried with pytorch 1.4.0, tensorboard 2.2.1 and tensorboardX 2.0, and everything is working properly.
I do not know what your logkeyModel_train.py does, but your issue seems rather related to the tensorboard/tensorboardx projects, which may be better places to look for a solution.
