### ISSUE TITLE
About the experiment.py

### ISSUE THREAD

**Issue by AIwuya** [eleurent/social-attention#2]
Hi, whether the experiment.py is not released?

**Comment by eleurent** [comment]
Hi @AIwuya,
Sorry, the README.md was not very clear (I'll fix it).
The `experiments.py` script is that of [rl-agents](https://github.com/eleurent/rl-agents)

You can clone the project and run it directly:
```
git clone git@github.com:eleurent/rl-agents.git
cd rl-agents/scripts/
python experiments.py [options]
```

**Comment by AIwuya** [comment]
> Hi @AIwuya,
> Sorry, the README.md was not very clear (I'll fix it).
> The `experiments.py` script is that of [rl-agents](https://github.com/eleurent/rl-agents)
> 
> You can clone the project and run it directly:
> 
> ```
> git clone git@github.com:eleurent/rl-agents.git
> cd rl-agents/scripts/
> python experiments.py [options]
> ```

Thank you, eleurent~
